kind: pipeline
name: default

steps:
- name: build
  image: rust:1-buster
  commands:
  - rustup component add rustfmt
  - cargo build --all
  - cargo test --all
- name: docker
  image: plugins/docker
  settings:
    repo: x7gv/reportas-server
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
    - master
    - dev
